# Generated by Django 4.1.5 on 2023-01-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero')),
            ],
        ),
    ]
